import type { Metadata } from 'next';
import Link from 'next/link';

import { PageShell } from '@/components/layout/page-shell';
import { MethodBasicsSections } from '@/components/method/sections-basics';
import { MethodDetailSections } from '@/components/method/sections-detail';
import { companyName } from '@/lib/company/names';
import { loadMethodPage } from '@/lib/method/page-data';
import { PULSE_DEMO_COMPANY_ID } from '@/lib/pulse/demo';
import { companyIdFromQuery, companyRoutes } from '@/lib/routes';

export const metadata: Metadata = {
  title: 'Método · Embat Pulse',
};

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

interface MethodPageProps {
  /** Carries the company in context as `?company=COMP_0001`. */
  searchParams: Promise<{ company?: string | string[] }>;
}

/**
 * How the PULSE of a month is built, told so that it needs no finance: the
 * idea in three drawings, what the number means, the four pillars with an
 * everyday comparison each, the 100 points, the four steps with a real month,
 * what a missing datum does, that month added by hand, what the score does
 * after the month, the formula and a glossary.
 *
 * @param props - Query parameters of the route.
 * @returns The method page.
 */
export default async function MethodPage({ searchParams }: MethodPageProps) {
  const { company: companyQuery } = await searchParams;
  const contextId = companyIdFromQuery(companyQuery);
  const data = await loadMethodPage(contextId);
  const { meta } = data;

  return (
    <PageShell
      title="Método"
      lead={`${meta.scoreName} (${meta.scoreExpansion}) es la nota de salud del dinero de una empresa: un número de 0 a 100, como en el colegio. Aquí se explica cómo sale ese número, sin palabras raras y con un mes real de ejemplo.`}
      aside={
        <Link
          data-arrow
          href={companyRoutes(contextId ?? PULSE_DEMO_COMPANY_ID).pulse}
          className="group inline-flex items-center gap-1.5 text-[15px] font-medium leading-[1.2] text-ink"
        >
          {contextId
            ? `Volver a ${companyName(contextId)}`
            : `Ver un PULSE: ${companyName(PULSE_DEMO_COMPANY_ID)}`}
          <i
            aria-hidden
            className="not-italic transition-transform group-hover:translate-x-1"
          >
            →
          </i>
        </Link>
      }
    >
      <MethodBasicsSections data={data} />
      <MethodDetailSections data={data} />
    </PageShell>
  );
}
