import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { AdvisorHeader } from '@/components/advisor/advisor-header';
import { DeclinedList } from '@/components/advisor/declined-list';
import { ImprovementPlanPanel } from '@/components/advisor/improvement-plan';
import { InputsPanel } from '@/components/advisor/inputs-panel';
import { OfferCard } from '@/components/advisor/offer-card';
import { RiskPanel } from '@/components/advisor/risk-panel';
import { PageShell, Section } from '@/components/layout/page-shell';
import { getAdvisorDataSource } from '@/lib/advisor/data';
import { companyName } from '@/lib/company/names';
import { formatMonth, formatNumber } from '@/lib/format';
import { getPulseDataSource } from '@/lib/pulse/data';

interface AdvisorPageProps {
  params: Promise<{ id: string }>;
}

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

/**
 * Builds the tab title from the company name.
 *
 * @param props - Route parameters.
 * @returns Page metadata.
 */
export async function generateMetadata({
  params,
}: AdvisorPageProps): Promise<Metadata> {
  const { id } = await params;
  return { title: `${companyName(id)} — Recomendaciones · Embat Pulse` };
}

/**
 * Writes the lead sentence from the counts, so it never repeats the score and
 * the confidence the header already shows.
 *
 * @param fitting - Products that fit.
 * @param declined - Products left out.
 * @returns One sentence saying how many products fit today.
 */
function buildLead(fitting: number, declined: number): string {
  if (fitting === 0) {
    return 'Hoy ningún producto supera el encaje mínimo; el plan de mejora dice qué lo desbloquearía.';
  }
  const fit =
    fitting === 1
      ? 'Un producto encaja hoy con la situación de la empresa'
      : `${formatNumber(fitting)} productos encajan hoy con la situación de la empresa`;
  const out =
    declined === 1
      ? 'uno queda fuera por sus reglas.'
      : `${formatNumber(declined)} quedan fuera por sus reglas.`;
  return `${fit}; ${out}`;
}

/**
 * Financial products recommended for one company: which ones fit, how much,
 * at what price, what would make that price cheaper and which products were
 * left out.
 *
 * @param props - Route parameters carrying the company identifier.
 * @returns The advisor page, or a 404 when the identifier is unknown.
 */
export default async function CompanyAdvisorPage({ params }: AdvisorPageProps) {
  const { id } = await params;
  const [company, summary] = await Promise.all([
    getAdvisorDataSource().getCompany(id),
    getPulseDataSource().getSummary(),
  ]);
  if (!company) notFound();

  const variableLabels = Object.fromEntries(
    summary.meta.variables.map((variable) => [variable.key, variable.label]),
  );
  const { recommendations, declined, improvementPlan } = company;
  const catalogueSize = recommendations.length + declined.length;
  const showPlan =
    improvementPlan.unlocks.length > 0 || improvementPlan.story.length > 0;

  return (
    <PageShell
      title={companyName(company.companyId)}
      lead={buildLead(recommendations.length, declined.length)}
    >
      <AdvisorHeader company={company} />
      {recommendations.length > 0 && (
        <Section
          title="Productos recomendados"
          note={`${formatNumber(recommendations.length)} de ${formatNumber(catalogueSize)} del catálogo, por orden de encaje`}
        >
          <div className="flex flex-col gap-6">
            {recommendations.map((offer) => (
              <OfferCard
                key={offer.product}
                offer={offer}
                referenceLabel={company.referenceRate.label}
                variableLabels={variableLabels}
              />
            ))}
          </div>
        </Section>
      )}
      {showPlan && (
        <Section
          title="Plan de mejora"
          note={
            recommendations.length === 0
              ? `Ningún producto supera el encaje mínimo de 40 con el PULSE de ${formatMonth(company.month)}`
              : 'Qué desbloquearía el resto del catálogo'
          }
        >
          <ImprovementPlanPanel plan={improvementPlan} />
        </Section>
      )}
      <Section
        title="Productos descartados"
        note="Con la regla que los deja fuera"
      >
        <DeclinedList declined={declined} />
      </Section>
      <Section
        title="Riesgo"
        note="Aportes al logit del modelo de tensión a seis meses"
      >
        <RiskPanel risk={company.risk} />
      </Section>
      <Section
        title="Datos usados"
        note={`Cierre de ${formatMonth(company.month)}`}
      >
        <InputsPanel inputs={company.inputs} />
      </Section>
      <p className="max-w-3xl text-xs text-muted">{company.disclaimer}</p>
    </PageShell>
  );
}
