import Link from 'next/link';

import { CompanyPicker } from '@/components/entry/company-picker';
import { getPulseDataSource } from '@/lib/pulse/data';
import {
  PULSE_DEMO_COMPANY_ID,
  PULSE_DEMO_CREDIT_LINE_COMPANY_ID,
} from '@/lib/pulse/demo';
import { companyRoutes } from '@/lib/routes';
import { formatMonth, formatNumber } from '@/lib/format';

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

/**
 * Entry point: choose the company whose PULSE to open.
 *
 * The app never shows the portfolio; this page only lists identifiers so a
 * company can be reached, plus two examples that walk through every screen.
 *
 * @returns The company picker and the example shortcuts.
 */
export default async function EntryPage() {
  const { meta, companies } = await getPulseDataSource().getSummary();
  const ids = companies.map((row) => row.companyId).sort();
  const examples = [
    {
      id: PULSE_DEMO_COMPANY_ID,
      note: 'Ocho meses observados, dos variables sin datos y tres productos recomendados.',
    },
    {
      id: PULSE_DEMO_CREDIT_LINE_COMPANY_ID,
      note: 'Veinticuatro meses observados y utilización de líneas conocida.',
    },
  ].filter((example) => ids.includes(example.id));

  return (
    <main className="mx-auto flex max-w-7xl flex-col gap-12 px-5 pb-20 pt-10 sm:px-8 sm:pt-16">
      <div className="flex max-w-2xl flex-col gap-3">
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          Tu empresa, mes a mes
        </h1>
        <p className="text-muted">
          {meta.scoreName} resume la salud financiera de una empresa en 100
          puntos a partir de sus movimientos bancarios y su ERP, con la
          previsión a seis meses y los productos financieros que encajan con su
          situación.
        </p>
      </div>

      <section className="flex flex-col gap-3">
        <h2 className="text-lg font-semibold tracking-tight">
          Abre una empresa
        </h2>
        {ids.length === 0 ? (
          <p className="text-sm text-muted">
            No hay export de PULSE disponible. Genera{' '}
            <code>src/data/pulse</code> o apunta <code>PULSE_API_URL</code> al
            servicio.
          </p>
        ) : (
          <>
            <CompanyPicker companyIds={ids} />
            <p className="text-sm text-muted">
              {formatNumber(ids.length)} empresas con cierre de{' '}
              {formatMonth(meta.lastMonth)}.
            </p>
          </>
        )}
      </section>

      {examples.length > 0 && (
        <section className="flex flex-col gap-3">
          <h2 className="text-lg font-semibold tracking-tight">Ejemplos</h2>
          <ul className="grid gap-x-10 gap-y-4 sm:grid-cols-2">
            {examples.map((example) => (
              <li key={example.id} className="flex flex-col gap-1">
                <Link
                  href={companyRoutes(example.id).pulse}
                  className="font-mono text-sm font-medium underline-offset-4 hover:underline"
                >
                  {example.id}
                </Link>
                <p className="text-sm text-muted">{example.note}</p>
              </li>
            ))}
          </ul>
        </section>
      )}
    </main>
  );
}
