import { ScoreHistogram } from '@/components/charts/score-histogram';
import { PillarHeatmap } from '@/components/charts/pillar-heatmap';
import { PageShell, Section } from '@/components/layout/page-shell';
import { MoversList } from '@/components/radar/movers-list';
import { PortfolioTable } from '@/components/radar/portfolio-table';
import { StatGrid } from '@/components/xray/stat-grid';
import { formatNumber, formatPercent } from '@/lib/xray/format';
import { getDataSource } from '@/lib/xray/data';

/** The dataset is regenerated by the ML service, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

/**
 * Portfolio radar: the entry point of Embat Pulse.
 *
 * It answers the question the risk team asks every month — which of the 1.286
 * companies changed, in which direction, and whether the change is structural.
 *
 * @returns The ranked portfolio with its distribution, movers and heatmap.
 */
export default async function RadarPage() {
  const source = getDataSource();
  const [summary, movers] = await Promise.all([
    source.getSummary(),
    source.getMovers({ limit: 10 }),
  ]);
  const { stats, meta } = summary;
  const deterioratingShare =
    stats.total === 0 ? 0 : stats.deteriorating / stats.total;

  return (
    <PageShell
      title="Radar de cartera"
      lead="Score mensual 0-100 de cada pyme, con la dirección de los últimos seis meses y el régimen detectado. Ordena por lo que se mueve, no por lo que ya ha pasado."
    >
      <StatGrid
        columns={5}
        items={[
          {
            key: 'total',
            label: 'Empresas puntuadas',
            value: formatNumber(stats.total),
            hint: `${formatNumber(meta.companyCount)} en el dataset`,
          },
          {
            key: 'median',
            label: 'Score mediano',
            value: formatNumber(stats.medianScore, 1),
          },
          {
            key: 'deteriorating',
            label: 'Deteriorándose',
            value: formatNumber(stats.deteriorating),
            hint: `${formatPercent(deterioratingShare, 1)} de la cartera`,
          },
          {
            key: 'decline',
            label: 'Caída estructural',
            value: formatNumber(stats.structuralDecline),
            hint: 'Cambio de nivel confirmado por PELT',
          },
          {
            key: 'stress',
            label: 'Prob. estrés ≥ 35 %',
            value: formatNumber(stats.highStress),
            hint: 'Horizonte de seis meses',
          },
        ]}
      />

      <div className="grid gap-10 lg:grid-cols-[1fr_1fr]">
        <Section title="Distribución de scores" note="Ancho de banda: 5 puntos">
          <ScoreHistogram bins={summary.histogram} />
        </Section>
        <Section
          title="Movimientos a seis meses"
          note="Variación del score frente a hace 6 meses"
        >
          <div className="grid gap-8 sm:grid-cols-2">
            <MoversList
              title="Mayores mejoras"
              rows={movers.improvers}
              tone="positive"
            />
            <MoversList
              title="Mayores deterioros"
              rows={movers.decliners}
              tone="negative"
            />
          </div>
        </Section>
      </div>

      <Section title="Cartera">
        <PortfolioTable rows={summary.rows} />
      </Section>

      <Section
        title="Pilares de las 20 empresas con peor score"
        note="Verde alto, rojo bajo; cada celda es el pilar sobre 100"
      >
        <PillarHeatmap rows={summary.worst} labels={meta.pillarLabels} />
      </Section>
    </PageShell>
  );
}
