import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { PageShell, Section } from '@/components/layout/page-shell';
import { PulseSignalKindLegend } from '@/components/pulse/signal-kind-legend';
import { PulseSignalTimeline } from '@/components/pulse/signal-timeline';
import { PulseSignalsHeader } from '@/components/pulse/signals-header';
import { companyName } from '@/lib/company/names';
import { getPulseDataSource } from '@/lib/pulse/data';
import { buildSignalsView } from '@/lib/pulse/signals-view';
import { formatMonth, formatNumber } from '@/lib/format';

interface SignalsPageProps {
  params: Promise<{ id: string }>;
}

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

/**
 * Builds the tab title from the company name.
 *
 * @param props - Route parameters.
 * @returns Page metadata.
 */
export async function generateMetadata({
  params,
}: SignalsPageProps): Promise<Metadata> {
  const { id } = await params;
  return { title: `${companyName(id)} — Señales · Embat Pulse` };
}

/**
 * Writes the lead sentence from the counts.
 *
 * @param open - Episodes still open.
 * @param total - Every episode found.
 * @param lastMonth - Last observed month.
 * @returns One sentence saying what is open and how much history there is.
 */
function buildLead(open: number, total: number, lastMonth: string): string {
  const closing = lastMonth ? ` hasta ${formatMonth(lastMonth)}` : '';
  if (total === 0) {
    return `La nota nunca se ha alejado de su media de forma clara${closing}.`;
  }
  const opened =
    open === 0
      ? 'Ninguna alerta abierta'
      : open === 1
        ? 'Una alerta abierta'
        : `${formatNumber(open)} alertas abiertas`;
  const history = total === 1 ? 'un mes' : `${formatNumber(total)} meses`;
  return `${opened}${closing}; la nota se movió de verdad en ${history}.`;
}

/**
 * Alerts and signals of one company: the episodes still open, what the model
 * said of them the month they opened, and every settled episode with what it
 * turned out to be.
 *
 * @param props - Route parameters carrying the company identifier.
 * @returns The signals page, or a 404 when the identifier is unknown.
 */
export default async function CompanySignalsPage({ params }: SignalsPageProps) {
  const { id } = await params;
  const company = await getPulseDataSource().getCompany(id);
  if (!company) notFound();
  const view = buildSignalsView(company.signals);

  return (
    <PageShell
      title={`Señales de ${companyName(company.companyId)}`}
      lead={buildLead(view.open.length, company.signals.length, company.month)}
      aside={<PulseSignalKindLegend />}
    >
      <PulseSignalsHeader company={company} view={view} />

      <Section
        title="Alertas abiertas"
        note="Aún sin tres meses de seguimiento; la probabilidad es la que dio el modelo al abrirse"
      >
        {view.open.length > 0 ? (
          <PulseSignalTimeline signals={view.open} />
        ) : (
          <p className="text-sm text-muted">
            Nada abierto: en los últimos tres meses la nota no se ha alejado de
            su media.
          </p>
        )}
      </Section>

      <Section
        title="Histórico"
        note="Episodios cerrados, del más reciente al más antiguo, con lo que fueron"
      >
        {view.settled.length > 0 ? (
          <PulseSignalTimeline signals={view.settled} />
        ) : (
          <p className="text-sm text-muted">Ningún episodio cerrado todavía.</p>
        )}
      </Section>
    </PageShell>
  );
}
