import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { AdvisorDetail } from '@/components/advisor/advisor-detail';
import { ApprovedPanel } from '@/components/advisor/approved-panel';
import { OutOfScopePanel } from '@/components/advisor/out-of-scope-panel';
import { PageShell } from '@/components/layout/page-shell';
import { companyName } from '@/lib/company/names';
import { formatNumber } from '@/lib/format';
import { loadCompanyPage } from '@/lib/pulse/company-page';

interface AdvisorPageProps {
  params: Promise<{ id: string }>;
}

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

/**
 * Builds the tab title from the company name.
 *
 * @param props - Route parameters.
 * @returns Page metadata.
 */
export async function generateMetadata({
  params,
}: AdvisorPageProps): Promise<Metadata> {
  const { id } = await params;
  return { title: `${companyName(id)} — Financiación · Embat Pulse` };
}

/**
 * Writes the lead sentence from the counts, so it never repeats the score and
 * the confidence the rest of the page can quote.
 *
 * @param fitting - Products that fit.
 * @param declined - Products left out.
 * @returns One sentence saying how many products fit today.
 */
function buildLead(fitting: number, declined: number): string {
  if (fitting === 0) {
    return `Los ${formatNumber(declined)} productos del catálogo quedan hoy fuera por sus reglas.`;
  }
  const fit =
    fitting === 1
      ? 'Un producto encaja hoy con la situación de la empresa'
      : `${formatNumber(fitting)} productos encajan hoy con la situación de la empresa`;
  const out =
    declined === 1
      ? 'uno queda fuera por sus reglas.'
      : `${formatNumber(declined)} quedan fuera por sus reglas.`;
  return `${fit}; ${out}`;
}

/**
 * What the company can contract this month: the products it can sign today
 * with their amount, their price and their fit, then the ones the rules leave
 * out with the rule that stops each of them, and finally the argument behind
 * the whole answer folded away.
 *
 * The page no longer opens with the operational measure that costs nothing:
 * that measure is an action, not an offer, so it lives on the Acción page and
 * the summary links to it. Whoever lands here has already decided to look at
 * financing, and the catalogue is what answers that.
 *
 * @param props - Route parameters carrying the company identifier.
 * @returns The advisor page, or a 404 when the identifier is unknown.
 */
export default async function CompanyAdvisorPage({ params }: AdvisorPageProps) {
  const { id } = await params;
  const data = await loadCompanyPage(id, true);
  const company = data?.advisor;
  if (!data || !company) notFound();

  const { meta } = data;
  const variableLabels = Object.fromEntries(
    meta.variables.map((variable) => [variable.key, variable.label]),
  );
  const pillarLabels = Object.fromEntries(
    meta.pillars.map((pillar) => [pillar.key, pillar.label]),
  );

  return (
    <PageShell
      title={companyName(company.companyId)}
      lead={buildLead(company.recommendations.length, company.declined.length)}
    >
      <ApprovedPanel
        company={company}
        pillarLabels={pillarLabels}
        variableLabels={variableLabels}
      />
      <OutOfScopePanel
        declined={company.declined}
        disclaimer={company.disclaimer}
      />
      <AdvisorDetail company={company} />
    </PageShell>
  );
}
