import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { CompanyActionsSection } from '@/components/actions/company-actions-panel';
import { AdvisorDetail } from '@/components/advisor/advisor-detail';
import { ApprovedPanel } from '@/components/advisor/approved-panel';
import { PageShell } from '@/components/layout/page-shell';
import { getAdvisorDataSource } from '@/lib/advisor/data';
import { companyName } from '@/lib/company/names';
import { formatNumber } from '@/lib/format';
import { getPulseDataSource } from '@/lib/pulse/data';

interface AdvisorPageProps {
  params: Promise<{ id: string }>;
}

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

/**
 * Builds the tab title from the company name.
 *
 * @param props - Route parameters.
 * @returns Page metadata.
 */
export async function generateMetadata({
  params,
}: AdvisorPageProps): Promise<Metadata> {
  const { id } = await params;
  return { title: `${companyName(id)} — Financiación · Embat Pulse` };
}

/**
 * Writes the lead sentence from the counts, so it never repeats the score and
 * the confidence the rest of the page can quote.
 *
 * @param fitting - Products that fit.
 * @param declined - Products left out.
 * @returns One sentence saying how many products fit today.
 */
function buildLead(fitting: number, declined: number): string {
  if (fitting === 0) {
    return `Los ${formatNumber(declined)} productos del catálogo quedan hoy fuera por sus reglas.`;
  }
  const fit =
    fitting === 1
      ? 'Un producto encaja hoy con la situación de la empresa'
      : `${formatNumber(fitting)} productos encajan hoy con la situación de la empresa`;
  const out =
    declined === 1
      ? 'uno queda fuera por sus reglas.'
      : `${formatNumber(declined)} quedan fuera por sus reglas.`;
  return `${fit}; ${out}`;
}

/**
 * What the company should do about its financing this month: the action
 * first, then the products it can sign today with their price and fit, and
 * the argument behind them folded away.
 *
 * @param props - Route parameters carrying the company identifier.
 * @returns The advisor page, or a 404 when the identifier is unknown.
 */
export default async function CompanyAdvisorPage({ params }: AdvisorPageProps) {
  const { id } = await params;
  const [company, summary] = await Promise.all([
    getAdvisorDataSource().getCompany(id),
    getPulseDataSource().getSummary(),
  ]);
  if (!company) notFound();

  const variableLabels = Object.fromEntries(
    summary.meta.variables.map((variable) => [variable.key, variable.label]),
  );
  const pillarLabels = Object.fromEntries(
    summary.meta.pillars.map((pillar) => [pillar.key, pillar.label]),
  );

  return (
    <PageShell
      title={companyName(company.companyId)}
      lead={buildLead(company.recommendations.length, company.declined.length)}
    >
      <CompanyActionsSection companyId={company.companyId} current="advisor" />
      <ApprovedPanel
        company={company}
        pillarLabels={pillarLabels}
        variableLabels={variableLabels}
      />
      <AdvisorDetail company={company} />
    </PageShell>
  );
}
