import type { Metadata } from 'next';
import Link from 'next/link';

import { PageShell, Section } from '@/components/layout/page-shell';
import { MethodConfidenceBar } from '@/components/method/confidence-bar';
import { MethodExamplePanel } from '@/components/method/example-panel';
import { MethodOutlookList } from '@/components/method/outlook-list';
import { MethodPipelineFlow } from '@/components/method/pipeline-flow';
import { MethodScoreScale } from '@/components/method/score-scale';
import { MethodWeightMap } from '@/components/method/weight-map';
import { companyName } from '@/lib/company/names';
import {
  buildConfidenceSegments,
  buildMethodExample,
} from '@/lib/method/example';
import { getPulseDataSource } from '@/lib/pulse/data';
import { PULSE_DEMO_COMPANY_ID } from '@/lib/pulse/demo';
import { companyIdFromQuery, companyRoutes } from '@/lib/routes';
import { formatMonth, formatNumber } from '@/lib/format';

export const metadata: Metadata = {
  title: 'Método · Embat Pulse',
};

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

interface MethodPageProps {
  /** Carries the company in context as `?company=COMP_0001`. */
  searchParams: Promise<{ company?: string | string[] }>;
}

/**
 * How the PULSE of a month is built, in plain words: the scale, the 100
 * points, the four steps of the calculation, a real month added by hand, and
 * three sentences on what the score does beyond the month.
 *
 * @param props - Query parameters of the route.
 * @returns The method page.
 */
export default async function MethodPage({ searchParams }: MethodPageProps) {
  const { company: companyQuery } = await searchParams;
  const contextId = companyIdFromQuery(companyQuery);
  const pulse = getPulseDataSource();
  const [{ meta }, requested] = await Promise.all([
    pulse.getSummary(),
    pulse.getCompany(contextId ?? PULSE_DEMO_COMPANY_ID),
  ]);
  const company =
    requested ??
    (contextId ? await pulse.getCompany(PULSE_DEMO_COMPANY_ID) : null);
  const example = buildMethodExample(company, meta.variables, meta.pillars);
  const coverage = buildConfidenceSegments(
    meta.variables,
    company?.series[company.series.length - 1] ?? null,
  );
  const lastHorizon = meta.horizons[meta.horizons.length - 1] ?? 12;

  return (
    <PageShell
      title="Método"
      lead={`${meta.scoreName} (${meta.scoreExpansion}) es una nota de 0 a 100 de la salud financiera de una empresa. Cada mes se miran ${formatNumber(meta.variables.length)} variables agrupadas en ${formatNumber(meta.pillars.length)} pilares —cobrar a tiempo, tener caja, deber poco y pagar bien—, cada una recibe su nota y cada nota vale unos puntos. La suma es el PULSE.`}
      aside={
        <Link
          className="text-sm text-accent underline-offset-4 hover:underline"
          href={companyRoutes(contextId ?? PULSE_DEMO_COMPANY_ID).pulse}
        >
          {contextId
            ? `Volver a ${companyName(contextId)}`
            : `Ver un PULSE: ${companyName(PULSE_DEMO_COMPANY_ID)}`}
        </Link>
      }
    >
      <Section
        title="La escala"
        note="Cuatro bandas, las mismas en toda la aplicación"
      >
        <MethodScoreScale
          caption={`Último cierre publicado: ${formatMonth(meta.lastMonth)}.`}
        />
      </Section>

      <Section
        title="Los 100 puntos"
        note="El tamaño de cada celda son sus puntos; pulsa una para ver qué mide"
      >
        <MethodWeightMap pillars={meta.pillars} variables={meta.variables} />
      </Section>

      <Section title="Cómo se calcula" note="Cuatro pasos, cada mes">
        <div className="flex flex-col gap-8">
          <MethodPipelineFlow />
          <MethodConfidenceBar
            segments={coverage}
            confidence={example?.confidence ?? null}
            caption={
              example
                ? `Datos de ${companyName(example.companyId)} en ${formatMonth(example.month)}: una variable sin datos no baja la nota, deja de contar.`
                : 'Sin mes observado para ilustrar la cobertura.'
            }
          />
        </div>
      </Section>

      <Section
        title="Un mes real, sumado a mano"
        note={
          example
            ? `${companyName(example.companyId)} · cierre de ${formatMonth(example.month)}`
            : 'Sin empresa de ejemplo'
        }
      >
        {example ? (
          <MethodExamplePanel example={example} />
        ) : (
          <p className="text-sm text-muted">
            El export no trae ninguna empresa con meses observados.
          </p>
        )}
      </Section>

      <Section
        title="Previsión, precio y límites"
        note="Lo demás, en tres frases"
      >
        <MethodOutlookList
          forecast={meta.evaluation.forecast}
          lastHorizon={lastHorizon}
        />
      </Section>
    </PageShell>
  );
}
