import type { Metadata } from 'next';
import Link from 'next/link';

import { PageShell, Section } from '@/components/layout/page-shell';
import { MethodConfidenceBar } from '@/components/method/confidence-bar';
import { MethodExamplePanel } from '@/components/method/example-panel';
import { MethodForecastTable } from '@/components/method/forecast-table';
import { MethodPipelineFlow } from '@/components/method/pipeline-flow';
import { MethodPricingPanel } from '@/components/method/pricing-panel';
import { MethodScopeList } from '@/components/method/scope-list';
import { MethodScoreEvaluation } from '@/components/method/score-evaluation';
import { MethodScoreScale } from '@/components/method/score-scale';
import { MethodWeightMap } from '@/components/method/weight-map';
import { getAdvisorDataSource } from '@/lib/advisor/data';
import { companyName } from '@/lib/company/names';
import {
  buildConfidenceSegments,
  buildMethodExample,
} from '@/lib/method/example';
import { getPulseDataSource } from '@/lib/pulse/data';
import { PULSE_DEMO_COMPANY_ID } from '@/lib/pulse/demo';
import { companyIdFromQuery, companyRoutes } from '@/lib/routes';
import { formatMonth, formatNumber } from '@/lib/format';

export const metadata: Metadata = {
  title: 'Método · Embat Pulse',
};

/** The export is regenerated by the backend, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

interface MethodPageProps {
  /** Carries the company in context as `?company=COMP_0001`. */
  searchParams: Promise<{ company?: string | string[] }>;
}

/**
 * How PULSE is built: the 100 points, the pipeline, a worked month, what the
 * score anticipates, how the forecast is validated and how a score becomes a
 * price.
 *
 * @param props - Query parameters of the route.
 * @returns The method page.
 */
export default async function MethodPage({ searchParams }: MethodPageProps) {
  const { company: companyQuery } = await searchParams;
  const contextId = companyIdFromQuery(companyQuery);
  const pulse = getPulseDataSource();
  const [{ meta }, requested, catalogue] = await Promise.all([
    pulse.getSummary(),
    pulse.getCompany(contextId ?? PULSE_DEMO_COMPANY_ID),
    getAdvisorDataSource().getCatalogue(),
  ]);
  const company =
    requested ??
    (contextId ? await pulse.getCompany(PULSE_DEMO_COMPANY_ID) : null);
  const example = buildMethodExample(company, meta.variables, meta.pillars);
  const coverage = buildConfidenceSegments(
    meta.variables,
    company?.series[company.series.length - 1] ?? null,
  );
  const lastHorizon = meta.horizons[meta.horizons.length - 1] ?? 6;

  return (
    <PageShell
      title="Método"
      lead={`${meta.scoreName} —${meta.scoreExpansion}— es un percentil mensual de salud financiera de 0 a 100: ${formatNumber(meta.variables.length)} variables repartidas en ${formatNumber(meta.pillars.length)} pilares, calculadas con extractos bancarios, facturas del ERP y productos de deuda.`}
      aside={
        <Link
          className="text-sm text-accent underline-offset-4 hover:underline"
          href={companyRoutes(contextId ?? PULSE_DEMO_COMPANY_ID).pulse}
        >
          {contextId
            ? `Volver a ${companyName(contextId)}`
            : `Ver un PULSE: ${companyName(PULSE_DEMO_COMPANY_ID)}`}
        </Link>
      }
    >
      <Section
        title="La escala"
        note="Un punto es un percentil de la población"
      >
        <MethodScoreScale
          caption={`Bandas fijas del producto, idénticas en tabla, gráfico y oferta. Último cierre publicado: ${formatMonth(meta.lastMonth)}.`}
        />
      </Section>

      <Section
        title="Anatomía de los 100 puntos"
        note="El área de cada celda son sus puntos"
      >
        <MethodWeightMap pillars={meta.pillars} variables={meta.variables} />
      </Section>

      <Section
        title="Del extracto al score"
        note="En el orden en que se ejecuta"
      >
        <div className="flex flex-col gap-8">
          <MethodPipelineFlow />
          <MethodConfidenceBar
            segments={coverage}
            confidence={example?.confidence ?? null}
            caption={
              example
                ? `Cobertura real de ${companyName(example.companyId)} en ${formatMonth(example.month)}: una variable sin datos no cuenta como cero, reduce la base sobre la que se mide.`
                : 'Sin mes observado para ilustrar la cobertura.'
            }
          />
        </div>
      </Section>

      <Section
        title="Cómo se lee un mes"
        note={
          example
            ? `${companyName(example.companyId)} · cierre de ${formatMonth(example.month)}`
            : 'Sin empresa de ejemplo'
        }
      >
        {example ? (
          <MethodExamplePanel example={example} />
        ) : (
          <p className="text-sm text-muted">
            El export no trae ninguna empresa con meses observados.
          </p>
        )}
      </Section>

      <Section
        title="Qué anticipa el score"
        note="Objetivo: episodio de estrés en los seis meses siguientes"
      >
        <MethodScoreEvaluation
          score={meta.evaluation.score}
          variables={meta.variables}
        />
      </Section>

      <Section
        title={`Previsión a ${formatNumber(lastHorizon)} meses`}
        note="Validación por grupo de empresa, fuera de muestra"
      >
        <div className="flex flex-col gap-5">
          <p className="max-w-3xl text-sm text-muted">
            Un modelo por horizonte predice el cambio de <code>pulse_raw</code>{' '}
            —el punto de partida es que el score se quede donde está— y dos
            modelos de cuantiles dibujan la banda p10-p90. Las contribuciones
            del modelo se reparten entre las{' '}
            {formatNumber(meta.variables.length)} variables más «contexto» y
            «base», de forma que las partes suman exactamente el cambio
            previsto, y el resultado vuelve a la escala 0-100 con la calibración
            congelada.
          </p>
          <MethodForecastTable
            horizons={meta.evaluation.forecast}
            emptyText="El export no publica la validación de la previsión."
          />
          <p className="max-w-3xl text-sm text-muted">
            El MAE está en puntos de PULSE y la ganancia se mide contra
            persistencia. «Dirección» es el acierto del signo en los movimientos
            de más de 15 puntos, y las dos columnas siguientes, la parte de esas
            caídas y de esas mejoras que el modelo vio venir. Las caídas se
            anticipan mucho mejor que las recuperaciones: léelo como un aviso
            temprano, no como un pronóstico simétrico.
          </p>
        </div>
      </Section>

      <Section
        title="De la puntuación al producto"
        note={`Referencia ${catalogue.referenceRate.label}`}
      >
        <MethodPricingPanel catalogue={catalogue} />
      </Section>

      <Section title="Qué no hace PULSE" note="Límites declarados">
        <MethodScopeList />
      </Section>
    </PageShell>
  );
}
