import type { Metadata } from 'next';

import { PageShell, Section } from '@/components/layout/page-shell';
import { FeatureTable } from '@/components/method/feature-table';
import { PipelineSteps } from '@/components/method/pipeline-steps';
import { StatGrid } from '@/components/xray/stat-grid';
import { getDataSource } from '@/lib/xray/data';
import {
  FALLBACK_METRICS,
  groupFeaturesByPillar,
  metricsFromAnticipation,
  type MethodMetric,
} from '@/lib/xray/method';

export const metadata: Metadata = {
  title: 'Método · Embat Pulse',
};

/** The dataset is regenerated by the ML service, so never freeze it at build time. */
export const dynamic = 'force-dynamic';

/**
 * Método: how the score is built and what it has been measured against.
 *
 * When the ML service publishes `evaluation.json` its numbers are shown as
 * they come; otherwise the headline figures of the model are shown and marked
 * explicitly as such.
 *
 * @returns The pipeline, the variable catalogue and the evaluation numbers.
 */
export default async function MethodPage() {
  const source = getDataSource();
  const [meta, evaluation, anticipation] = await Promise.all([
    source.getMeta(),
    source.getEvaluation(),
    source.getAnticipation(),
  ]);
  const groups = groupFeaturesByPillar(meta.featureLabels, meta.featurePillars);
  const published: MethodMetric[] = evaluation.present
    ? Object.entries(evaluation.metrics).map(([label, value]) => ({
        key: label,
        label,
        value: String(value),
      }))
    : metricsFromAnticipation(anticipation);
  const metrics = published.length > 0 ? published : FALLBACK_METRICS;
  const measured = published.length > 0;

  return (
    <PageShell
      title="Método"
      lead="Cómo se construye el score X-Ray, con qué se ha validado y qué significan sus seis pilares."
    >
      <Section
        title="Resultados"
        note={
          measured
            ? `Medidos sobre ${meta.companyCount.toLocaleString('es-ES')} empresas y ${meta.groupCount.toLocaleString('es-ES')} grupos`
            : 'Cifras declaradas del modelo; el servicio aún no publica evaluación'
        }
      >
        <StatGrid columns={5} items={metrics} />
      </Section>

      <Section title="De los extractos al score">
        <PipelineSteps />
      </Section>

      <Section
        title="Variables por pilar"
        note={`${Object.keys(meta.featureLabels).length} variables mensuales`}
      >
        <FeatureTable groups={groups} labels={meta.pillarLabels} />
      </Section>

      <Section title="Qué no hace el score">
        <ul className="flex max-w-3xl flex-col gap-2 text-sm text-muted">
          <li>
            No usa información externa —registros de morosidad, ratings o
            cuentas anuales—: solo movimientos bancarios, facturas y deuda de la
            propia empresa.
          </li>
          <li>
            No predice la quiebra: predice un evento de estrés de tesorería en
            los seis meses siguientes, que es lo que la plataforma puede
            observar y lo que afecta a una línea de circulante.
          </li>
          <li>
            No decide por sí solo: el límite y el precio de Embat Capital son
            una regla explícita sobre el score, auditable y reproducible.
          </li>
        </ul>
      </Section>

      <Section title="Origen de los datos">
        <p className="max-w-3xl text-sm text-muted">
          {meta.generatedFor}. {meta.companyCount.toLocaleString('es-ES')}{' '}
          empresas en {meta.groupCount.toLocaleString('es-ES')} grupos, con
          hasta 24 meses de historia mensual. La validación cruzada se hace por
          grupo: ninguna empresa del mismo grupo se usa a la vez para entrenar y
          para medir.
        </p>
      </Section>
    </PageShell>
  );
}
